### ISSUE TITLE
[BUG]Kruner theme not change

### ISSUE THREAD

**Issue by Littleweisheit** [baduhai/Koi#56] opened 2022-08-22 13:57 UTC
1.daylight shutdown computer
2.boot OS at night.Krunner theme not change.
https://github.com/baduhai/Koi/issues/53#issue-1323479057

**Comment by baduhai** [comment] 2022-10-10 11:16
What Plasma and Koi versions are you running? Also, what distro?

**Comment by esiha** [comment] 2022-11-04 08:24
I have the same behavior when I shut down my computer with night theme on and turn it back on the next morning : KRunner theme remains black (instead the font that is correctly set, which makes it hard to read as it becomes black on black).

Distro : Debian bookworm (testing), Plasma 5.26
Koi : master@ffcf703 (ahead of 0.2.3)

**Comment by MartinVonReichenberg** [comment] 2022-11-04 09:46
After updating KDE Plasma to 5.26.x it started behaving with KWin remaining still, requiring the whole desktop to be refreshed in order to switch from dark to light and to from light to dark.

**Comment by baduhai** [comment] 2022-11-04 09:50
I havê a feeling thus is an upstream issue, and not Koi's problemas necessarily.

**Comment by vroger11** [comment] 2022-11-30 09:14
Using `kquitapp5 plasmashell && kstart5 plasmashell` don't even solve this problem

**Comment by vroger11** [comment] 2022-11-30 09:21
It seems to be linked with krunner as `krunner --replace -d` does the trick

**Comment by oodzchen** [comment] 2023-06-10 00:45
This still happen to me, on Fedora 38, I've manual installed the latest Koi from this repository. Every time after switch the theme, krunner remain previous state, I need to logout the system and login again to make it work.

**Comment by baduhai** [comment] 2023-06-10 00:48
I won't be making any efforts to fix this for two reasons. 1. I can not reproduce the bug. 2. Plasma is getting built in support for this functionality in 6.0

Sorry.

**Comment by MartinVonReichenberg** [comment] 2023-11-04 00:31
Fixed with commit 386c0fe from @vroger11  . . .

**Closed** 2023-11-04 01:21 UTC
Labels: bug
